### ISSUE TITLE
Run MegaDetector locally

### ISSUE THREAD

**Issue by treyworley** [kbowerma/c4c#10]
Download the appropriate files needed to run MegaDetector locally
**TODO**
- [ ] Find correct model files needed & download them to repo
- [ ] Use a notebook to test making predictions on local images in `/images` dir
- [ ] Get predictions for both
  - [ ] isAnimal?
  - [ ] animal_species
